config/routes.rb
Rails.application.routes.draw do
	root to: 'students#index'
	resources :students
	resources :schools, only: [:show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
	belongs_to :school
	belongs_to :student
end

app/models/school.rb
class School < ApplicationRecord
	has_many :clients, dependent: :destroy
	has_many :students, through: :clients

	validates :name, presence: true
end

app/models/student.rb
class Student < ApplicationRecord
	before_save { self.email = email.downcase }
  before_save { self.name = name.capitalize }

	has_many :clients, dependent: :destroy
	has_many :schools, through: :clients

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	
	validates :name, presence: true
	validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
	def index
		@schools = School.all.order('name ASC')
	end

	def show
		@school = School.find(params[:id])
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def index
		@students = Student.all.order("name ASC") 
	end

	def new
		@schools = School.all
		@student = Student.new
	end

	def create
		@schools = School.all
		@student = Student.new(student_params)
		if @student.save 
			redirect_to "/"
		else
			flash[:alert] = "Please review the information provided"
			render 'new'
		end
	end

	def edit
		@schools = School.all
		@student = Student.find(params[:id])
	end

	def update
		@student = Student.find(params[:id])
		@student.update(student_params)
		redirect_to "/"
	end

	def destroy
		@student = Student.find(params[:id])
		@student.destroy
		flash[:notice] = "Student deleted successfully"
		redirect_to "/"
	end

	private
		def student_params
			params.require(:student).permit(:name, :email, :school_ids, school_ids: [])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToucanTech</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice %>
    <%= alert %>
  	<div class="container">
  		<%= yield %>
  	</div>
  </body>
</html>

app/views/schools/index.html.erb
<header>
  <h1>Schools</h1>
</header>
<table class="rwd-table">
  <thead>
    <tr>
      <th>School</th>
    </tr>
  </thead>
  <tbody>
    <% @schools.each do |school| %>
    <tr>
      <td data-th="Schools"><%= link_to school.name, school_path(school), class: "btn btn-info btn-md" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back', students_path, class: "btn btn-success btn-lg" %>

app/views/schools/show.html.erb
<header>
  <h1>
    <%= @school.name %> Students
  </h1>
</header>
<table class="rwd-table">
  <thead>
    <tr>
      <th>Student</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @school.students.each do |student| %>
    <tr>
      <td data-th="Name"><%= student.name %></td>
      <td data-th="Delete"><%= link_to "Delete #{student.name}", student_path(student), method: :delete, class: "btn btn-danger btn-md" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back', schools_path, class: "btn btn-success btn-lg" %>

app/views/students/_form.html.erb
<%= form_for @student, :html => {:class => "form-inline"} do |f| %>
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :email %>
		<%= f.text_field :email, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :school %>	
		<div class="form-dropdown">		
			<%= f.collection_select(:school_ids, School.all, :id, :name, {}, {multiple: true}) %>
		</div>
	</div>
	<%= f.submit "Submit", class: "btn btn-default btn-primary" %>
<% end %> 

app/views/students/edit.html.erb
<h1>Edit Student</h1>

<%= render 'form' %>

app/views/students/index.html.erb
<section>
	<header>
		<h1>Students</h1>
	</header>
	<table class="rwd-table">
		<thead>
			<tr>
				<th>Name</th>
				<th>Email</th>
				<th>Schools</th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<%if @students.any? %>
        <% @students.each do |student| %>
          <tr>
            <td data-th="Name"><%= student.name %></td>
            <td data-th="Email"><%= student.email %></td>
            <td data-th="Schools">
              <%student.schools.each do |school| %>
                <br>  <%= school.name%>
              <% end %>
            </td>
            <td data-th="Edit">
            	<%= link_to "Edit #{student.name}", edit_student_path(student), class: "btn btn-info btn-md"  %>
            </td>
            <td data-th="Delete">
            	<%= link_to "Delete #{student.name}", student_path(student), method: :delete, class: "btn btn-danger btn-md" %>
            </td>
          </tr>
        <% end %>
      <% else %>
        <h1>No students to show</h1>
      <% end %>
		</tbody>
	</table>
	<%= link_to 'Add a student', new_student_path, class: "btn btn-success btn-lg" %> <br><br>
	<%= link_to "View schools",  schools_path, class: "btn btn-success btn-lg" %>
</section>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>
<br />
To select more than one school please use cmd
<br><br>
<%= link_to 'Back', students_path, class: "btn btn-success btn-lg" %>